


"                       plugins
" ---------------------------------------------------------------

"set nocompatible
"filetype off
" Set the runtime path to include plug and initialize
"set rtp+=~/.vim/autoload/plug.vim
" Download plug-ins to the ~/.vim/plugged/ directory
call plug#begin('~/.vim/plugged')
Plug 'sheerun/vim-polyglot'

"colors
Plug 'AlessandroYorba/Sierra'
Plug 'arcticicestudio/nord-vim'
Plug 'cocopon/iceberg.vim'
Plug 'Badacadabra/vim-archery'
Plug 'kristijanhusak/vim-hybrid-material'
Plug 'scheakur/vim-scheakur'
Plug 'morhetz/gruvbox'

Plug 'derekwyatt/vim-fswitch'
Plug 'preservim/nerdtree'
Plug 'jeffkreeftmeijer/vim-numbertoggle' " no line number in nerdtree
Plug 'preservim/tagbar'
Plug 'dyng/ctrlsf.vim'
Plug 'derekwyatt/vim-protodef'
"Plug 'kien/ctrlp.vim'
Plug 'airblade/vim-gitgutter'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'tpope/vim-fugitive'
Plug 'rhysd/vim-clang-format'
"Plug 'wfxr/minimap.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'puremourning/vimspector'
Plug 'ilyachur/cmake4vim'
Plug 'ntpeters/vim-better-whitespace'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'chengzeyi/fzf-preview.vim'
Plug 'ryanoasis/vim-devicons'
call plug#end()
filetype plugin indent on
" ---------------------------------------------------------------


source /home/aunai/.config/dotfiles/vim/fzfconf.vim
source /home/aunai/.config/dotfiles/vim/gitgutter.vim
"source /home/aunai/.config/dotfiles/vim/cmake4vim.vim
source /home/aunai/.config/dotfiles/vim/nerdtree.vim
source /home/aunai/.config/dotfiles/vim/cocvim.vim
source /home/aunai/.config/dotfiles/vim/tagbar.vim
source /home/aunai/.config/dotfiles/vim/ctrlsf.vim
"source /home/aunai/.config/dotfiles/vim/vimspector.vim
source /home/aunai/.config/dotfiles/vim/stripwhitespace.vim
"source /home/aunai/.config/dotfiles/vim/cocexplorer.vim
source /home/aunai/.config/dotfiles/vim/fugitive.vim






" this sets the relative line number
" only on the active buffer
set number relativenumber                               " line numbers
augroup numbertoggle
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
    autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

syntax on                                               " syntax colors
set nowrap                      " do not wrap lines at righ side terminal
let mapleader = " "             " user special key
set ruler                       " show cursor position in status bar
set showcmd                     " show typed command in status bar
set title                       " show file in title bar
set showmatch                   " show matching brackets
set showmode                    " show mode insert,replace etc. in status bar
set wildmenu                    " completion with menu
set laststatus=2                " use 2 lines for the status bar
set matchtime=2                 " show matching brackets for 0.2 seconds
set incsearch                   " incremental search
set noerrorbells                " no annoying sound on errors
set path+=/usr/include/**,.,**  " add current dir to path and subdirs recursively
set mouse=a                     " cool for scrolling
set scrolloff=10
set viewoptions-=options        " do not take options into acount when saving
set colorcolumn=80              " show column 80
highlight colorcolumn guibg=#A3D3DB
set nohlsearch
set backspace=indent,eol,start
set background=dark
colorscheme gruvbox
set cursorline                  " highlight cursor line

" system settings
set hidden                      " remember undo after quitting
set history=100                 " keeps 100 lines of command history
set matchpairs+=<:>             " specifically for html




" file name completion
set wildmenu                                            " set it on
set wildmode=longest,list                               " similar to the shell
set wildignore+=*.a,*.o,*.pyc                           " ignore those stupid files
set wildignore+=*.pyc
set wildignore+=**/coverage/*
set wildignore+=**/.git/*


" indentation
set tabstop=8                                           " tab is 8 spaces
set shiftwidth=4                                        " an indent is 4 spaces
set expandtab                                           " hitting tab will produce the appropriate # of spaces
set autoindent                                          " copy the indentation of the previous line to the current
set softtabstop=4
filetype plugin indent on


" --------- vimrc ------------------------------------------------------------
"nnoremap sv :source $MYVIMRC<cr>
"nnoremap ev :e $MYVIMRC<cr>
nnoremap sv :source ~/.vimrc<cr>
nnoremap ev :e ~/.vimrc<cr>
" ----------------------------------------------------------------------------


" terminal
set termwinsize=12x0   " Set terminal size

" --------- splits -----------------------------------------------------------
"Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
set splitbelow         " Always split below
nnoremap <Leader>cl :close<CR>
nnoremap <Leader>v :vs<CR><C-w>l
nnoremap <Leader>h :sp<CR>
" Make adjusing split sizes a bit more friendly
noremap <silent> <C-Left> :vertical resize +3<CR>
noremap <silent> <C-Right> :vertical resize -3<CR>
noremap <silent> <C-Up> :resize +3<CR>
noremap <silent> <C-Down> :resize -3<CR>

" Change 2 split windows from vert to horiz or horiz to vert
map <Leader>th <C-w>t<C-w>H
map <Leader>tk <C-w>t<C-w>K
nnoremap <Leader>w  :Buffers<CR>
" ----------------------------------------------------------------------------






" invisible characters
set list                                                " show them
set listchars=tab:\⇒\─,trail:\‣,extends:\↷,precedes:\↶  " how they appear



" Set internal encoding of vim, not needed on neovim, since coc.nvim using some
" unicode characters in the file autoload/float.vim
set encoding=utf-8


" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup

" Give more space for displaying messages.
set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

"------------------------------------------------------------------------------

" transparent bg
"autocmd vimenter * hi Normal guibg=NONE ctermbg=NONE
" For Vim<8, replace EndOfBuffer by NonText
"autocmd vimenter * hi EndOfBuffer guibg=NONE ctermbg=NONE


function! ReTab()
  let &tabstop = &shiftwidth
  retab!
  let &tabstop = 8
endfunction



"---------------------minimap -----------------------
"let g:minimap_width = 10
"let g:minimap_auto_start = 0
"let g:minimap_auto_start_win_enter = 0
"-----------------------------------------------------

" folding  :http://www.linux.com/learn/tutorials/442438-vim-tips-folding-fun
set foldmethod=manual                                   " folding manually
"au BufWinLeave * mkview                                 " save the folds before leaving
"au BufWinEnter * silent loadview                        " restore folds when opening
set fdc =2                                              " put a vertical bar indicating where folds are



" yank into clipboard
set clipboard=unnamedplus
nnoremap <Leader>y "+y
nnoremap <Leader>p "+p



" cycling through buffers
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>



" -----------------------------------------------------------------------------
"   CLANG FORMAT
" -----------------------------------------------------------------------------

autocmd FileType cpp ClangFormatAutoEnable
let g:clang_format#detect_style_file=1
let g:clang_format#auto_format_on_insert_leave=1
let g:clang_format#auto_format=0

" samrai C files recognized as cpp
autocmd BufReadPre *.C set ft=cpp

" -----------------------------------------------------------------------------



" -----------------------------------------------------------------------------
"   EDITING REMAPS
" -----------------------------------------------------------------------------

" moving lines up and down
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
inoremap <C-j> :m .+1<CR>==
inoremap <C-k> :m ._2<CR>==
nnoremap <Leader>k :m .-2<CR>==
nnoremap <Leader>j :m .+1<CR>==
" -----------------------------------------------------------------------------

